[build]
  base = "funbide-app"
  command = "npm --prefix funbide-app/funbide-app run build"
  publish = "funbide-app/funbide-app/dist/funbide-app/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/tv"
  to = "/tv/index.html"
  status = 200
