insert into public.servicios_precios (codigo, nombre, area_destino, categoria, precio) values
('COM001', 'ENERGÃA ELÃ‰CTRICA', 'Consulta Externa', 'Consulta Externa', 0.00),
('COM002', 'COMUNICACIONES MÚLTIPLES', 'Consulta Externa', 'Consulta Externa', 0.00),
('COM003', 'ALQUILERES', 'Consulta Externa', 'Consulta Externa', 0.00),
('COM004', 'CONSUMO INTERNO', 'Consulta Externa', 'Consulta Externa', 0.00),
('COM005', 'TRANSPORTE Y MENSAJERÃA', 'Consulta Externa', 'Consulta Externa', 0.00),
('COM006', 'FLETES Y TRASPORTE', 'Consulta Externa', 'Consulta Externa', 0.00),
('COM007', 'NOMINA DE DOCTORES', 'Consulta Externa', 'Consulta Externa', 0.00),
('CUL001', 'CULTIVO', 'Cirugía', 'Cirugía', 8000.00),
('EV-PRE001', 'EVALUACION PRE-QUIRURGICA', 'EV-PRE', 'EV-PRE', 1500.00),
('EV-PSI001', 'EVALLUCION PSICOLOGICA', 'EV-PSI', 'EV-PSI', 1500.00),
('FAR001', 'ENTREGA MEDICAMENTO', 'Farmacia', 'Farmacia', 500.00),
('FAR002', 'GLICEMIA', 'Farmacia', 'Farmacia', 100.00),
('FAR003', 'EXAMEN DE LA VISTA', 'Farmacia', 'Farmacia', 200.00),
('FAR004', 'SOBRANTE DE TARJETA', 'Farmacia', 'Farmacia', 4.00),
('FAS001', 'SENASA SUBSIDIADO', 'Farmacia', 'Farmacia', 0.00),
('FAS002', 'SENASA COTRIBUTIVO', 'Farmacia', 'Farmacia', 1.00),
('FAS003', 'SENASA ODONTOLOGIA CONTRIBUTIVO', 'Farmacia', 'Farmacia', 0.00),
('FAS004', 'SENASA ODONTOLOGIA PLAN ESPECIAL', 'Farmacia', 'Farmacia', 0.00),
('FAS005', 'SENASA VOLUNTARIOS COLECTIVOS', 'Farmacia', 'Farmacia', 0.00),
('FAS006', 'SENASA PLAN ESPECIAL PENSIONADO', 'Farmacia', 'Farmacia', 0.00),
('FAS007', 'SENASA CONTRIBUTIVO FULL', 'Farmacia', 'Farmacia', 0.00),
('GNC001', 'CONDULTA', 'Consulta', 'Consulta', 0.00),
('GNC002', 'IMPLANON', 'Consulta', 'Consulta', 0.00),
('IMG001', 'RADIOGRAFÃA INTRAORAL PERIAPICAL MILIMET', 'Imagenología', 'Imagenología', 150.00),
('IMG002', 'RADIOGRAFÃA INTRAORAL PERIAPICAL MOLARES', 'Imagenología', 'Imagenología', 100.00),
('IMG003', 'RADIOGRAFÃA PANORÃMICA DE MAXILAR SUPERI', 'Imagenología', 'Imagenología', 320.00),
('IMG004', 'RADIOGRAFÃA PANORÃMICA DE MAXILAR SUPERI', 'Imagenología', 'Imagenología', 320.00),
('IMG005', 'RADIOGRAFÃA INTRAORAL PERIAPICAL PREMOLA', 'Imagenología', 'Imagenología', 100.00),
('IMG006', 'RADIOGRAFÃA INTRAORAL CORONALES', 'Imagenología', 'Imagenología', 150.00),
('IMG007', 'RADIOGRAFÃA INTRAORAL CORONALES', 'Imagenología', 'Imagenología', 150.00),
('IMG008', 'RADIOGRAFÃA INTRAORAL PERIAPICAL DIENTES', 'Imagenología', 'Imagenología', 100.00),
('IMG009', 'RADIOGRAFÃA INTRAORAL PERIAPICAL DIENTES', 'Imagenología', 'Imagenología', 100.00),
('IMG010', 'RADIOGRAFÃA INTRAORAL PERIAPICAL DIENTES', 'Imagenología', 'Imagenología', 100.00),
('IMG011', 'RADIOGRAFÃA INTRAORAL PERIAPICAL DIENTES', 'Imagenología', 'Imagenología', 100.00),
('IMG012', 'RADIOGRAFÃA INTRAORAL PERIAPICAL MILIMET', 'Imagenología', 'Imagenología', 100.00),
('IMG013', 'RADIOGRAFÃA INTRAORAL PERIAPICAL MOLARES', 'Imagenología', 'Imagenología', 100.00),
('IMG014', 'RADIOGRAFÃA INTRAORAL PERIAPICAL PREMOLA', 'Imagenología', 'Imagenología', 100.00),
('IMG015', 'RADIOGRAFÃA INTRAORAL PERIAPICAL ZONA DE', 'Imagenología', 'Imagenología', 100.00),
('IMG016', 'RADIOGRAFÃA INTRAORAL PERIAPICAL ZONA DE', 'Imagenología', 'Imagenología', 100.00),
('IMG017', 'SONOGRAFÃA DE TIROIDE', 'Imagenología', 'Imagenología', 600.00),
('IMG018', 'SONOGRAFÃA ABDOMINAL', 'Imagenología', 'Imagenología', 600.00),
('IMG019', 'SONOGRAFÃA PÃ‰LVICA', 'Imagenología', 'Imagenología', 600.00),
('IMG020', 'SONOGRAFÃA TRANSVAGINAL', 'Imagenología', 'Imagenología', 600.00),
('IMG021', 'SONOGRAFÃA OBSTÃ‰TRICA', 'Imagenología', 'Imagenología', 600.00),
('IMG022', 'SONOGRAFÃA ESCROTAL', 'Imagenología', 'Imagenología', 600.00),
('IMG023', 'SONOGRAFÃA PROSTÃTICA', 'Imagenología', 'Imagenología', 600.00),
('IMG024', 'SONOGRAFÃA DE PARTES BLANDAS', 'Imagenología', 'Imagenología', 600.00),
('IMG025', 'ESTUDIO COLORACIÃ“N BÃSICA EN CITOLOGÃA', 'Imagenología', 'Imagenología', 700.00),
('IMG026', 'SONOGRAFÃA MAMARIAS', 'Imagenología', 'Imagenología', 600.00),
('LAB001', 'HEMOGRAMA', 'Laboratorio', 'Laboratorio', 200.00),
('LAB002', 'GLICEMIA', 'Laboratorio', 'Laboratorio', 0.00),
('LAB003', 'UREA', 'Laboratorio', 'Laboratorio', 0.00),
('LAB004', 'CULTIVO DE SECRECION VAGINAL', 'Laboratorio', 'Laboratorio', 0.00),
('LAB005', 'CULTIVO ORINA', 'Laboratorio', 'Laboratorio', 0.00),
('LAB006', 'TSH', 'Laboratorio', 'Laboratorio', 0.00),
('LAB007', 'T3', 'Laboratorio', 'Laboratorio', 0.00),
('LAB008', 'T4', 'Laboratorio', 'Laboratorio', 0.00),
('LAB009', 'T4/LIBRE', 'Laboratorio', 'Laboratorio', 0.00),
('LAB010', 'HDL', 'Laboratorio', 'Laboratorio', 300.00),
('LAB011', 'LDL', 'Laboratorio', 'Laboratorio', 300.00),
('LAB012', 'COLESTEROL TOTAL', 'Laboratorio', 'Laboratorio', 300.00),
('LAB013', 'COPROLOGICO', 'Laboratorio', 'Laboratorio', 300.00),
('LAB014', 'TGO', 'Laboratorio', 'Laboratorio', 250.00),
('LAB015', 'TGP', 'Laboratorio', 'Laboratorio', 250.00),
('LAB016', 'ORINA', 'Laboratorio', 'Laboratorio', 300.00),
('LAB017', 'CREATININA', 'Laboratorio', 'Laboratorio', 250.00),
('LAB018', 'TIPIFICACION SANQUINIA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB019', 'TOXOPLAMOSIS', 'Laboratorio', 'Laboratorio', 350.00),
('LAB020', 'NITROGENO UREICO', 'Laboratorio', 'Laboratorio', 300.00),
('LAB021', 'FALCEMIA', 'Laboratorio', 'Laboratorio', 300.00),
('LAB022', 'HCV HEPATITIS C', 'Laboratorio', 'Laboratorio', 400.00),
('LAB023', 'HBS AG. HEPATITIS B', 'Laboratorio', 'Laboratorio', 350.00),
('LAB024', 'CULTIVO DE SECRECION NASAL', 'Laboratorio', 'Laboratorio', 350.00),
('LAB025', 'HEPATITIS A -IGM', 'Laboratorio', 'Laboratorio', 400.00),
('LAB026', 'HEPATITIS C -HVC', 'Laboratorio', 'Laboratorio', 400.00),
('LAB027', 'HEMOGLOBINA GLICOSILADA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB028', 'HEMOCULTIVO', 'Laboratorio', 'Laboratorio', 450.00),
('LAB029', 'HCG CUATITATIVA', 'Laboratorio', 'Laboratorio', 250.00),
('LAB030', 'VITAMINA D', 'Laboratorio', 'Laboratorio', 1100.00),
('LAB031', 'FRASCO DE UROCULTIVO', 'Laboratorio', 'Laboratorio', 50.00),
('LAB032', 'FRASCO DE HEMOCULTIVO', 'Laboratorio', 'Laboratorio', 300.00),
('LAB033', 'FOSFORO', 'Laboratorio', 'Laboratorio', 0.00),
('LAB034', 'FALCEMIA', 'Laboratorio', 'Laboratorio', 300.00),
('LAB035', 'ESTROGENOS TOTALES', 'Laboratorio', 'Laboratorio', 400.00),
('LAB036', 'ERITROSEDIMENTACION', 'Laboratorio', 'Laboratorio', 300.00),
('LAB037', 'ACIDO FOLICO', 'Laboratorio', 'Laboratorio', 300.00),
('LAB038', 'CLORO', 'Laboratorio', 'Laboratorio', 300.00),
('LAB039', 'CLORURO', 'Laboratorio', 'Laboratorio', 300.00),
('LAB040', 'CALCIO', 'Laboratorio', 'Laboratorio', 300.00),
('LAB041', 'BILIRRUBINA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB042', 'DHGG CUANTITATIVA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB043', 'COCAINA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB044', 'COLESTEROL TOTAL', 'Laboratorio', 'Laboratorio', 300.00),
('LAB045', 'COLESTEROL HDL', 'Laboratorio', 'Laboratorio', 300.00),
('LAB046', 'COLESTEROL DLD', 'Laboratorio', 'Laboratorio', 300.00),
('LAB047', 'CONTEO DE PLAQUETAS', 'Laboratorio', 'Laboratorio', 300.00),
('LAB048', 'COPROCULTIVO', 'Laboratorio', 'Laboratorio', 400.00),
('LAB049', 'CREATITINA EN SUERO', 'Laboratorio', 'Laboratorio', 250.00),
('LAB050', 'CULTIVOS DE HECES', 'Laboratorio', 'Laboratorio', 400.00),
('LAB051', 'CULTIVO DE SECRECION VAGINAL', 'Laboratorio', 'Laboratorio', 350.00),
('LAB052', 'CULTIVO DE SECRECION SEMEN', 'Laboratorio', 'Laboratorio', 400.00),
('LAB053', 'B- HCG CUANTITATIVA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB054', 'ANTI TIROGLABUTINA', 'Laboratorio', 'Laboratorio', 450.00),
('LAB055', 'ANTI-DNA', 'Laboratorio', 'Laboratorio', 600.00),
('LAB056', 'AMONIO', 'Laboratorio', 'Laboratorio', 350.00),
('LAB057', 'TPT TIEMPO TROMBOPLASTINA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB058', 'TP TIEMPO PROTROMBINA', 'Laboratorio', 'Laboratorio', 350.00),
('LAB059', 'DIMERO D CUANTITATIVO', 'Laboratorio', 'Laboratorio', 950.00),
('LAB060', 'ACIDO URICO', 'Laboratorio', 'Laboratorio', 300.00),
('MED001', 'CONSULTA MEDICINA GENERAL', 'Consulta Médica', 'Medicina General', 600.00),
('MED002', 'CONSULTA DIABETOLOGÃA', 'Consulta Médica', 'Medicina General', 600.00),
('MED003', 'CONSULTA MEDICINA FAMILIAR', 'Consulta Médica', 'Medicina General', 600.00),
('MED004', 'CONSULTA SONOGRAFÃA', 'Consulta Médica', 'Medicina General', 600.00),
('MED005', 'CONSULTA ORTOPEDIA', 'Consulta Médica', 'Medicina General', 600.00),
('MED006', 'CONSULTA NUTRICIONISTA', 'Consulta Médica', 'Medicina General', 600.00),
('MED007', 'CONSULTA GERIATRÃA', 'Consulta Médica', 'Medicina General', 600.00),
('MED008', 'CONSULTA MEDICINA INTERNA', 'Consulta Médica', 'Medicina General', 600.00),
('MED009', 'CONSULTA GASTROENTEROLOGÃA', 'Consulta Médica', 'Medicina General', 600.00),
('MED010', 'CONSULTA PEDIATRÃA', 'Consulta Médica', 'Medicina General', 600.00),
('MED011', 'CONSULTA PSICOLÃ“GICA', 'Consulta Médica', 'Medicina General', 600.00),
('MED012', 'CONSULTA CARDIOLOGÃA', 'Consulta Médica', 'Medicina General', 600.00),
('MED013', 'CONSULTA GINECOBSTETRA', 'Consulta Médica', 'Medicina General', 600.00),
('MED014', 'TEST DE FAMILIA', 'Consulta Médica', 'Medicina General', 600.00),
('MED015', 'TEST DE FIGURA HUMANA', 'Consulta Médica', 'Medicina General', 600.00),
('MED016', 'TEST DE RAVEN', 'Consulta Médica', 'Medicina General', 600.00),
('MED017', 'TERAPIA DE DEPRESIÃ“N Y ANSIEDAD', 'Consulta Médica', 'Medicina General', 600.00),
('MED018', 'TERAPIA FAMILIAR', 'Consulta Médica', 'Medicina General', 600.00),
('MED019', 'TERAPIA DE PAREJA', 'Consulta Médica', 'Medicina General', 600.00),
('MED020', 'CONSULTA NEFROLOGÃA', 'Consulta Médica', 'Medicina General', 600.00),
('ODO001', 'CONSULTA ODONTOLÃ“GICA', 'Consultorio Dental', 'Odontología', 600.00),
('ODO002', 'ALISADO RADICULAR, CAMPO CERRADO SOD', 'Consultorio Dental', 'Odontología', 600.00),
('ODO003', 'APLICACIÃ“N DE RESINA PREVENTIVA', 'Consultorio Dental', 'Odontología', 300.00),
('ODO004', 'APLICACIÃ“N DE SELLANTES DE AUTOCURADO', 'Consultorio Dental', 'Odontología', 300.00),
('ODO005', 'APLICACIÃ“N DE SELLANTES DE FOTO CURADO', 'Consultorio Dental', 'Odontología', 300.00),
('ODO006', 'CIRUGÃA DE DIENTE INCLUIDO (INCLUYE COLG', 'Consultorio Dental', 'Odontología', 1220.00),
('ODO007', 'COLGAJO DESPLAZADO PARA ABORDAJE DE DIEN', 'Consultorio Dental', 'Odontología', 1740.00),
('ODO008', 'CONSULTA ODONTOLOGÃA GENERAL', 'Consultorio Dental', 'Odontología', 600.00),
('ODO009', 'CONSULTA ODONTOLÃ“GICA EMERGENCIA Y/O URG', 'Consultorio Dental', 'Odontología', 575.00),
('ODO010', 'CONSULTA ODONTOLÃ“GICA ESPECIALIZADA', 'Consultorio Dental', 'Odontología', 500.00),
('ODO011', 'CONTROL DE PLACA DENTAL NCOC (PROFILAXIS', 'Consultorio Dental', 'Odontología', 1000.00),
('ODO012', 'CURETAJE A CAMPO ABIERTO', 'Consultorio Dental', 'Odontología', 1800.00),
('ODO013', 'DETARTRAJE SUBGINGIVAL CUADRANTE INFERIO', 'Consultorio Dental', 'Odontología', 900.00),
('ODO014', 'DETARTRAJE SUBGINGIVAL CUADRANTE INFERIO', 'Consultorio Dental', 'Odontología', 900.00),
('ODO015', 'DETARTRAJE SUBGINGIVAL CUADRANTE SUPERIO', 'Consultorio Dental', 'Odontología', 900.00),
('ODO016', 'DETARTRAJE SUBGINGIVAL CUADRANTE SUPERIO', 'Consultorio Dental', 'Odontología', 900.00),
('ODO017', 'DETARTRAJE SUPRAGINGIVAL CUADRANTE INFER', 'Consultorio Dental', 'Odontología', 550.00),
('ODO018', 'DETARTRAJE SUPRAGINGIVAL CUADRANTE INFER', 'Consultorio Dental', 'Odontología', 550.00),
('ODO019', 'DETARTRAJE SUPRAGINGIVAL CUADRANTE SUPER', 'Consultorio Dental', 'Odontología', 550.00),
('ODO022', 'ESCISIÃ“N DE LESIÃ“N DE ENCÃA SOD U', 'Consultorio Dental', 'Odontología', 1000.00),
('ODO023', 'ESCISIÃ“N DE LESIÃ“N ODONTOGÃ‰NICA SOD l', 'Consultorio Dental', 'Odontología', 1000.00),
('ODO024', 'EXODONCIA DE DIENTE INCLUIDO SOD +', 'Consultorio Dental', 'Odontología', 500.00),
('ODO025', 'EXODONCIA DE DIENTE PERMANENTE MULTIRRAD', 'Consultorio Dental', 'Odontología', 720.00),
('ODO026', 'EXODONCIA DE DIENTE PERMANENTE UNIRRADIC', 'Consultorio Dental', 'Odontología', 600.00),
('ODO027', 'EXODONCIA DE DIENTE TEMPORAL MULTIRRADIC', 'Consultorio Dental', 'Odontología', 720.00),
('ODO028', 'EXODONCIA DE DIENTE TEMPORAL UNIRRADICUL', 'Consultorio Dental', 'Odontología', 600.00),
('ODO029', 'EXODONCIA DE INCLUIDO EN POSICIÃ“N ECTÃ“PI', 'Consultorio Dental', 'Odontología', 3000.00),
('ODO030', 'EXODONCIA QUIRÃšRGICA MULTIRRADICULARES S', 'Consultorio Dental', 'Odontología', 1300.00),
('ODO031', 'EXODONCIA QUIRÃšRGICA UNIRRADICULAR SOD', 'Consultorio Dental', 'Odontología', 1300.00),
('ODO032', 'EXODONCIAS MÚLTIPLES CON ALVEOLOPLASTIA,', 'Consultorio Dental', 'Odontología', 2150.00),
('ODO033', 'GINGIVECTOMÍA SOD', 'Consultorio Dental', 'Odontología', 1240.00),
('ODO034', 'REMOCIÃ“N DE CUERPO EXTRAÃ‘O EN TEJIDOS BL', 'Consultorio Dental', 'Odontología', 0.00),
('ODO035', 'TOPICACION DE FLÃšOR EN GEL', 'Consultorio Dental', 'Odontología', 300.00),
('ODO036', 'TOPICACION DE FLÃšOR EN SOLUCIÃ“N', 'Consultorio Dental', 'Odontología', 200.00),
('ODO037', 'PRÃ“TESIS COMPLETAS EN VALPLAST IMPLANTES', 'Consultorio Dental', 'Odontología', 12000.00),
('ODO038', 'IMPLANTES', 'Consultorio Dental', 'Odontología', 36000.00),
('ODO039', 'CORONAS SOBRE IMPLANTES', 'Consultorio Dental', 'Odontología', 18000.00),
('ODO040', 'OBTURACION CON RECINA CLASE I', 'Consultorio Dental', 'Odontología', 1100.00),
('ODO041', 'OBTURACION CON RECINA CLASE II', 'Consultorio Dental', 'Odontología', 1600.00),
('ODO042', 'OBTURACION CON RECINA CLASE III', 'Consultorio Dental', 'Odontología', 2000.00),
('ODO043', 'OBTURACION CON RECINA CLASE IV', 'Consultorio Dental', 'Odontología', 2500.00),
('ODO044', 'OBTURACION CON RECINA CLASE V', 'Consultorio Dental', 'Odontología', 3000.00),
('ODO045', 'CAMBIO DE GOMAS', 'Consultorio Dental', 'Odontología', 1000.00),
('ODO046', 'PARCIAL VALPLAST CENTRAL SUPERIOR', 'Consultorio Dental', 'Odontología', 13000.00),
('ODO047', 'CARILLAS ESTETICAS', 'Consultorio Dental', 'Odontología', 2600.00),
('ODO048', 'ORTODONCIA', 'Consultorio Dental', 'Odontología', 7500.00),
('ODO049', 'ENDODONCIA', 'Consultorio Dental', 'Odontología', 6000.00),
('ODO050', 'CAMBIO DE ARO', 'Consultorio Dental', 'Odontología', 1000.00),
('ODO051', 'CEMENTACION DE BLACK', 'Consultorio Dental', 'Odontología', 1000.00),
('ODO052', 'APLICACION DE COLTOSOL', 'Consultorio Dental', 'Odontología', 800.00),
('ODO053', 'PERIAPICAL', 'Consultorio Dental', 'Odontología', 400.00),
('ODO054', 'PROTESIS TOTAL REMOVIBLE', 'Consultorio Dental', 'Odontología', 11000.00),
('ORT001', 'ORTOPEDA', 'Ortopedia', 'Ortopedia', 500.00),
('PAO001', 'PAPANICOLAOU', 'Apoyo', 'Apoyo', 1499.89),
('PAO002', 'PAPANICOLAOU LIQUIDO', 'Apoyo', 'Apoyo', 1500.00),
('SEG001', 'ARS SENASA', 'Caja / Seguros', 'Seguro', 500.00),
('SEG002', 'ARS RENACER', 'Caja / Seguros', 'Seguro', 1.00),
('SEG003', 'HUMANO', 'Caja / Seguros', 'Seguro', 1.00),
('SEG004', 'APS ARS', 'Caja / Seguros', 'Seguro', 1.00),
('SEG101', 'SENASA SUBSIDIADO', 'Caja / Seguros', 'Seguro', 200.00),
('SEG102', 'SENASA CONTRIBUTIVO', 'Caja / Seguros', 'Seguro', 500.00),
('SEG103', 'SENASA ODONTOLOGIA CONTRIBUTIVO', 'Caja / Seguros', 'Seguro', 500.00),
('SEG104', 'SENASA ODONTOLOGIA PESP', 'Caja / Seguros', 'Seguro', 300.00),
('SEG105', 'SENASA PLAN ESPECIAL PENSIONADO', 'Caja / Seguros', 'Seguro', 500.00),
('SEG106', 'SENASA VOLUNTARIOS COLECTIVOS', 'Caja / Seguros', 'Seguro', 300.00)
on conflict (codigo) do update set
  nombre = excluded.nombre,
  area_destino = excluded.area_destino,
  categoria = excluded.categoria,
  precio = excluded.precio,
  updated_at = now();

