-- Seed generado desde listado de precios funbide.xlsx
-- Importa y reemplaza solo los codigos derivados del archivo Excel.

update public.servicios_precios set activo = false;

delete from public.servicios_precios where codigo in ('CM001', 'CM002', 'CM003', 'CM004', 'CM005', 'CM006', 'CM007', 'CM008', 'CM009', 'CM010', 'CM011', 'CM012', 'CM013', 'DX001', 'OBT001', 'OBT002', 'OBT003', 'OBT004', 'OBT005', 'OBT006', 'OBT007', 'OBT008', 'OBT009', 'OBT010', 'OBT011', 'ODO001', 'ODO002', 'ODO003', 'ODO004', 'ODO005', 'ODO006', 'ODO007', 'ODO008', 'ODO009', 'ODO010', 'ODO011', 'ODO012', 'ODO013', 'ODO014', 'ODO015', 'ODO016', 'ODO017', 'ODO018', 'ODO019', 'ODO020', 'ODO021', 'ODO022', 'ORT001', 'ORT002', 'ORT003', 'PRO001', 'PRO002', 'PRO003', 'PRO004', 'PRO005', 'PRO006', 'PRO007', 'PRO008', 'PRO009', 'PRO010', 'PRO011', 'PRO012', 'PRO013', 'PRO014', 'SON001', 'SON002', 'SON003', 'SON004', 'SON005', 'SON006', 'SON007', 'SON008', 'SON009');

insert into public.servicios_precios (codigo, nombre, area_destino, categoria, precio, precio_subsidiado, precio_contributivo, aplica_seguro, activo) values
  ('CM001', 'CONSULTA MEDICINA GENERAL', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM002', 'CONSULTA MEDICO GINECOBSTETRA', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM003', 'CONSULTA MEDICO FAMILIAR', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM004', 'CONSULTA MEDICO INTERNISTA', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM005', 'CONSULTA MEDICO PEDIATRA', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM006', 'ESTUDIO DE COLORACION BASICA EN CITOLOGIA VAGINAL', 'Consultas Médicas', 'Consultas Médicas', 1000.00, 1000.00, 1000.00, true, true),
  ('CM007', 'CONSULTA MEDICO PSICOLOGO', 'Consultas Médicas', 'Consultas Médicas', 1000.00, 1000.00, 1000.00, true, true),
  ('CM008', 'TEST DE FAMILIA', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM009', 'TES DE FIGURA HUMANA', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM010', 'TEST DE RAVEN', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM011', 'TERAPIA DE DEPRESION Y ANSIEDAD', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM012', 'TERAPIA FAMILIAR', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('CM013', 'TERAPIA DE PAREJA', 'Consultas Médicas', 'Consultas Médicas', 600.00, 400.00, 100.00, true, true),
  ('SON001', 'SONOGRAFIA MAMARIAS.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON002', 'SONOGRAFIA DE TIROIDE.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON003', 'SONOGRAFIA ABDOMINAL.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON004', 'SONOGRAFIA PERVICA.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON005', 'SONOGRAFIA TRNSVAJINAL.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON006', 'SONOGRAFIA OSBTRETICA.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON007', 'SONOGRAFIA ESCROTAL.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON008', 'SONOGRAFIA PROSTATICA.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('SON009', 'SONOGRAFIA DE PARTES BLADAS.', 'Sonografías', 'Sonografías', 600.00, null, null, false, true),
  ('ODO001', 'CONSULTA ODONTOLOGICA EMERGENCIA Y/O URGENCIAS', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 600.00, null, null, false, true),
  ('ODO002', 'CONSULTA ODONTOLOGICA GENERAL', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 600.00, null, null, false, true),
  ('ODO003', 'APLICACIÓN DE SELLANTES DE  AUTOCURADO/POR CUADRANTE', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 600.00, null, null, false, true),
  ('ODO004', 'APLICACIÓN DE SELLANTES DE FOTOCURADO/POR CUADRANTE', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 600.00, null, null, false, true),
  ('ODO005', 'TOPICACION DE FLUOR EN GEL', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 600.00, null, null, false, true),
  ('ODO006', 'TOPICACION DE FLUOR EN SOLUCION', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 600.00, null, null, false, true),
  ('ODO007', 'CONTROL DE PLACA DENTAL NCOC', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 2000.00, null, null, false, true),
  ('ODO008', 'ESCISION DE LESION DE ENCIA SOD §', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 900.00, null, null, false, true),
  ('ODO009', 'EXODONCIA DE DIENTE PERMANENTE UNIRRADICULAR +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 1500.00, null, null, false, true),
  ('ODO010', 'EXODONCIA DE DIENTE PERMANENTE MULTIRRADICULAR +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 2000.00, null, null, false, true),
  ('ODO011', 'EXODONCIA DE DIENTE TEMPORAL UNIRRADICULAR +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 700.00, null, null, false, true),
  ('ODO012', 'EXODONCIA DE DIENTE TEMPORAL MULTIRRADICULAR +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 900.00, null, null, false, true),
  ('ODO013', 'EXODONCIA QUIRURGICA MULTIRRADICULAR SOD', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 900.00, null, null, false, true),
  ('ODO014', 'EXODONCIA QUIRURGICA UNIRRADICULAR SOD', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 1500.00, null, null, false, true),
  ('ODO015', 'EXODONCIAS MULTIPLES CON ALVEOLOPLASTIA, POR CUADRANTE SOD', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 3000.00, null, null, false, true),
  ('ODO016', 'EXODONCIAS TERCEROS MOLARES MUTILRADICULAR', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 3500.00, null, null, false, true),
  ('ODO017', 'DRENAJE DE COLECCION PERIODONTAL (CERRADO CON ALISADO RADICULAR) SOD+', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 4500.00, null, null, false, true),
  ('ODO018', 'DETARTRAJE SUBGINGIVAL SOD +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 1700.00, null, null, false, true),
  ('ODO019', 'DETARTRAJE SUPRAGINGIVAL SOD +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 1700.00, null, null, false, true),
  ('ODO020', 'GINGIVECTOMIA SOD', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 5000.00, null, null, false, true),
  ('ODO021', 'ALISADO RADICULAR, CAMPO CERRADO SOD +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 2000.00, null, null, false, true),
  ('ODO022', 'CURETAJE A CAMPO ABIERTO +', 'Procedimientos Odontológicos', 'Procedimientos Odontológicos', 2000.00, null, null, false, true),
  ('DX001', 'RADIOGRAFIAS INTRAORALES CORONALES', 'Apoyo Diagnóstico (Dx)', 'Apoyo Diagnóstico (Dx)', 600.00, null, null, false, true),
  ('OBT001', 'OBTURACION DENTAL CON RESINA FOTOCURADO CLASE I', 'Obturación', 'Obturación', 1100.00, null, null, false, true),
  ('OBT002', 'OBTURACION DENTAL CON RESINA FOTOCURADO CLASE II', 'Obturación', 'Obturación', 1600.00, null, null, false, true),
  ('OBT003', 'OBTURACION DENTAL CON RESINA FOTOCURADO CLASE III', 'Obturación', 'Obturación', 2000.00, null, null, false, true),
  ('OBT004', 'OBTURACION DENTAL CON RESINA FOTOCURADO CLASE IV', 'Obturación', 'Obturación', 2500.00, null, null, false, true),
  ('OBT005', 'OBTURACION DENTAL CON RESINA FOTOCURADO CLASE V', 'Obturación', 'Obturación', 3000.00, null, null, false, true),
  ('OBT006', 'RECONSTRUCCION DEL ANGULO INCISAL CON RESINA DE FOTOCURADO', 'Obturación', 'Obturación', 2000.00, null, null, false, true),
  ('OBT007', 'PULPOTOMIA SOD', 'Obturación', 'Obturación', 1500.00, null, null, false, true),
  ('OBT008', 'ENDODONCIA DTE. ANTERIOR (TRATAMIENTO DE CANAL)', 'Obturación', 'Obturación', 6000.00, null, null, false, true),
  ('OBT009', 'ENDODONCIA PREMOLAR (TRATAMIENTO DE CANAL)', 'Obturación', 'Obturación', 8000.00, null, null, false, true),
  ('OBT010', 'ENDODONCIA MOLAR (TRATAMIENTO DE CANAL)', 'Obturación', 'Obturación', 12000.00, null, null, false, true),
  ('OBT011', 'EMERGENCIA ENDODONTICA', 'Obturación', 'Obturación', 12000.00, null, null, false, true),
  ('ORT001', 'BRACKETS', 'Ortodoncia', 'Ortodoncia', 7500.00, null, null, false, true),
  ('ORT002', 'SEGUIMIENTO BRACKETS', 'Ortodoncia', 'Ortodoncia', 1000.00, null, null, false, true),
  ('ORT003', 'CURA TRATAMIENTO EXPECTANTE', 'Ortodoncia', 'Ortodoncia', 700.00, null, null, false, true),
  ('PRO001', 'PROTESIS TOTAL ACRILICA C/U', 'Prótesis', 'Prótesis', 15000.00, null, null, false, true),
  ('PRO002', 'PROTESIS PARCIAL ACRILICA 1—4 PIEZAS', 'Prótesis', 'Prótesis', 15000.00, null, null, false, true),
  ('PRO003', 'PUENTE FIJO C/U', 'Prótesis', 'Prótesis', 15000.00, null, null, false, true),
  ('PRO004', 'CORONAS', 'Prótesis', 'Prótesis', 15000.00, null, null, false, true),
  ('PRO005', 'PERNO COLADO', 'Prótesis', 'Prótesis', 6000.00, null, null, false, true),
  ('PRO006', 'MERILAD', 'Prótesis', 'Prótesis', 17000.00, null, null, false, true),
  ('PRO007', 'PLACAS MIORELAJANTES', 'Prótesis', 'Prótesis', 7000.00, null, null, false, true),
  ('PRO008', 'PARCIAL VALPLAST 1-3', 'Prótesis', 'Prótesis', 13000.00, null, null, false, true),
  ('PRO009', 'PARCIAL VALPLAST 4-6', 'Prótesis', 'Prótesis', 14000.00, null, null, false, true),
  ('PRO010', 'PARCIAL VALPLAST 7-10', 'Prótesis', 'Prótesis', 17000.00, null, null, false, true),
  ('PRO011', 'UNILATERAL', 'Prótesis', 'Prótesis', 5500.00, null, null, false, true),
  ('PRO012', 'PROTESIS COMPLETAS EN VALPLAST', 'Prótesis', 'Prótesis', 12000.00, null, null, false, true),
  ('PRO013', 'IMPLANTES', 'Prótesis', 'Prótesis', 36000.00, null, null, false, true),
  ('PRO014', 'CORONAS SOBRE IMPLANTES', 'Prótesis', 'Prótesis', 18000.00, null, null, false, true);
